name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: fish-shop/install-fish-shell@v2
      - name: Install fisher and fishtape
        run: |
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
          fisher install jorgebucaran/fisher
          fisher install jorgebucaran/fishtape
        shell: fish {0}
      - name: Syntax check
        run: |
          fish --no-execute conf.d/autoreload.fish
          fish --no-execute completions/autoreload.fish
        shell: fish {0}
      - uses: fish-shop/run-fishtape-tests@v2
        with:
          patterns: tests/**.fish
